name: cours_web
description: "Cours Lycee Maroc - Version Web"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  dio: ^5.11.0
  shared_preferences: ^2.5.5
  google_fonts: ^8.2.1
  intl: ^0.20.3
  url_launcher: ^6.3.2
  syncfusion_flutter_pdfviewer: ^34.2.8
  web: ^1.1.1
  firebase_core: ^4.15.0
  firebase_auth: ^6.7.0
  google_sign_in: ^7.2.0
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
    - assets/audio/
    - assets/orientation/schools/
